Added async validator to Form group
Recursyve/ngx-form-generator pull request #60
Opened 2023-04-24 19:59 UTC by gabaudette

2023-04-25 01:09 UTC, JulienDuf approved these changes

2023-05-05 14:51 UTC, Jtplouffe requested changes

2023-05-08 13:16 UTC, Jtplouffe approved these changes

2023-05-08 13:16 UTC, Jtplouffe commented on projects/form-generator/src/lib/forms/generated-form.ts
> +    ) {
Manque le type de retour

2023-05-15 17:33 UTC, gabaudette commented
@JulienDuf Il faut mettre a jour la version

2023-05-15 17:33 UTC, merged